site_name: CTU.Word2Vec - Procon 2023
site_url: https://thangved.github.io/procon2023-docs
copyright: |
  &copy; 2023 CTU.Word2Vec
docs_dir: docs
remote_branch: gh-pages
site_description: CTU.Word2Vec - Procon 2023
site_author: CTU.Word2Vec
repo_url: https://github.com/thangved/procon2023-docs
repo_name: thangved/procon2023-docs

theme:
  name: material
  favicon: assets/logo-ctu.png
  language: vi
  logo: assets/logo-ctu.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - tags
  - offline
  - social
  - git-committers:
        repository: thangved/procon2023-docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thangved/procon2023-docs
    - icon: fontawesome/brands/facebook
      link: https://fb.com/thangved

markdown_extensions:
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
